adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h zmalloc.h config.h ae_kqueue.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
anet.o: anet.c fmacros.h anet.h
cluster.o: cluster.c prez.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h cluster.h endianconv.h
config.o: config.c prez.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h
crc64.o: crc64.c
db.o: db.c prez.h fmacros.h config.h ae.h sds.h dict.h adlist.h zmalloc.h \
  anet.h version.h util.h
debug.o: debug.c prez.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h
dict.o: dict.c fmacros.h dict.h zmalloc.h assert.h
endianconv.o: endianconv.c
log.o: log.c prez.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h cluster.h endianconv.h
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
networking.o: networking.c prez.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h zmalloc.h anet.h version.h util.h
object.o: object.c prez.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h
pqsort.o: pqsort.c
prez.o: prez.c prez.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h cluster.h
sds.o: sds.c sds.h zmalloc.h
sha1.o: sha1.c sha1.h config.h
util.o: util.c fmacros.h util.h sds.h
ziplist.o: ziplist.c zmalloc.h util.h sds.h ziplist.h endianconv.h \
  config.h assert.h
zipmap.o: zipmap.c zmalloc.h endianconv.h config.h
zmalloc.o: zmalloc.c config.h zmalloc.h
